default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  database: <%= ENV.fetch("DATABASE_NAME") %>

development:
  <<: *postgresql_settings

test:
  <<: *default
  database:  <%= ENV.fetch("TEST_DATABASE_NAME") %>
  user: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

production:
  <<: *postgresql_settings